// Generated by https://quicktype.io

export class Paciente {
    id:               number;
    nombre:           string;
    apellido:         string;
    fecha_nacimiento: Date;
    peso:             number;
    estatura:         number;
}

